version: '3.8'

services:
  kratos:
    image: oryd/kratos:v25.4.0
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    environment:
      - DSN=postgres://kratos:secret@postgres:5432/kratos?sslmode=disable
      - LOG_LEVEL=info
    volumes:
      - type: bind
        source: ./kratos/kratos.yaml
        target: /etc/config/kratos/kratos.yaml
      - type: bind
        source: ./kratos/identity.schema.json
        target: /etc/config/kratos/identity.schema.json
    command: serve -c /etc/config/kratos/kratos.yaml --dev --watch-courier
    restart: unless-stopped
    depends_on:
      - postgres
      - mailslurper

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"

  postgres:
    image: postgres:14
    ports:
      - "5433:5432"  # Use 5433 to avoid conflict with keto
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
    volumes:
      - kratos-postgres:/var/lib/postgresql/data

volumes:
  kratos-postgres:
